// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Token struct {
	Token string `json:"token"`
}

type User struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Followers []*User `json:"followers"`
}
