package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"fmt"

	"github.com/IlianBuh/GraphQL/internal/clients/sso"
	"github.com/IlianBuh/GraphQL/internal/graph/model"
	"github.com/IlianBuh/GraphQL/internal/lib/validate"
)

func (r *mutationResolver) SignUp(ctx context.Context, login string, email string, password string) (*model.Token, error) {
	if err := validate.SignUp(login, email, password); err != nil {
		return nil, sendErr(InvalidArgument, err)
	}

	token, err := r.SSO.SignUp(ctx, login, email, password)
	if err != nil {
		var ssoerr *sso.Error
		if errors.As(err, &ssoerr) {
			return nil, handleSsoError(ssoerr)
		}
		return nil, sendErr(Internal, err)
	}

	return &model.Token{Token: token}, nil
}

// LogIn is the resolver for the logIn field.
func (r *queryResolver) LogIn(ctx context.Context, login string, password string) (*model.Token, error) {
	if err := validate.LogIn(login, password); err != nil {
		return nil, sendErr(InvalidArgument, err)
	}

	token, err := r.SSO.LogIn(ctx, login, password)
	if err != nil {
		var ssoerr *sso.Error
		if errors.As(err, &ssoerr) {
			return nil, handleSsoError(ssoerr)
		}

		return nil, sendErr(Internal, err)
	}

	return &model.Token{Token: token}, nil
}

// ListFollowers is the resolver for the listFollowers field.
func (r *queryResolver) ListFollowers(ctx context.Context, userID int32) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: ListFollowers - listFollowers"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int32) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, id []int32) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
